apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apisix/
  - cloudflared/
  - argocd/

commonLabels:
  app.kubernetes.io/part-of: puchi-platform
  app.kubernetes.io/component: platform
