x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "myAwEsOm3pa55@w0rd"
  POSTGRES_USER: "user"

x-rabbitmq-variables: &x-rabbitmq-variables
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "admin"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  APP_NAME: "user-service"
  APP_VERSION: "1.0.0"
  HTTP_PORT: "8002"
  HTTP_USE_PREFORK_MODE: "false"
  LOG_LEVEL: "debug"
  PG_POOL_MAX: "2"
  PG_URL: "postgres://user:myAwEsOm3pa55@w0rd@user-db:5432/db"
  GRPC_PORT: "9002"
  RMQ_RPC_SERVER: "user_rpc_server"
  RMQ_RPC_CLIENT: "user_rpc_client"
  RMQ_URL: "amqp://admin:admin@rabbitmq:5672/"
  METRICS_ENABLED: "true"
  SWAGGER_ENABLED: "true"

services:
  db:
    container_name: user-db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # tránh conflict với auth-db
    networks:
      app_network:
        aliases:
          - user-db

  app:
    container_name: user-app
    platform: linux/amd64
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8002:8002"
      - "9002:9002"
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - user-app
      apisix:
        aliases:
          - user-app

  nginx:
    container_name: user-nginx
    image: nginx:1.29.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "82:80"  # tránh conflict với auth-nginx
    depends_on:
      - app
    networks:
      app_network:
        aliases:
          - user-nginx
      apisix:
        aliases:
          - user-nginx

networks:
  app_network:
    external: false
  apisix:
    external: true

volumes:
  db_data:
